app:
  name: gobase
  version: 1.0.0
  mode: development

server:
  host: "0.0.0.0"
  port: 8080
  timeout: 30s

logger:
  development: false
  level: "info"              # debug, info, warn, error
  format: "text"            # text, json
  reportCaller: true
  timeFormat: "RFC3339"
  disableConsole: false
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stderr"
  maxAge: "168h"            # 7天，日志保留时间
  rotationTime: "24h"       # 日志轮转时间
  maxSize: 100             # 单个日志文件最大大小(MB)
  rotation:
    enable: true
    filename: "logs/app.log"
    maxSize: 100            # MB
    maxAge: 7              # days
    rotationTime: "24h"
    maxBackups: 3
    compress: true
  compress:
    enable: true
    algorithm: "gzip"
    level: 9
    deleteSource: true
    interval: "1h"
  cleanup:
    enable: true
    maxBackups: 3
    maxAge: 7
    interval: "24h"
  async:
    enable: true
    bufferSize: 8192
    flushInterval: "1s"
    blockOnFull: false
    dropOnFull: true
    flushOnExit: true
  recovery:
    enable: true
    maxRetries: 3
    retryInterval: "1s"
    enableStackTrace: true
    maxStackSize: 4096
  queue:
    maxSize: 1000
    batchSize: 100
    workers: 1
    flushInterval: "1s"
    retryCount: 3
    retryInterval: "1s"
    maxBatchWait: "5s"
    shutdownTimeout: "10s"
  elk:
    enable: false

elk:
  addresses:
    - "http://localhost:9200"
  username: "username"
  password: "password"
  index: "logs"
  timeout: 30
  bulk:
    batchSize: 1000
    flushBytes: 5242880  # 5MB
    interval: 30s

database:
  postgres:
    host: localhost
    port: 9187
    user: db_username
    password: db_password
    dbname: db_name
    sslmode: disable
    timeout: "30s"

redis:
  addr: localhost:6379
  password: ""
  db: 0

kafka:
  brokers:
    - localhost:9092
  topic: gobase

consul:
  addr: localhost:8500
  token: ""

jaeger:
  endpoint: http://localhost:14268/api/traces

nacos:
  group: "DEFAULT_GROUP"